---

hostname: R6

isis_net: "49.0001.0000.0000.0006.00"
bgp_as: 65001

loopback:
  name: Loopback0
  ipv4: "192.168.0.6"
  prefix_length: 32

interfaces:
  - name: GigabitEthernet0/0/0/0
    description: "LINK-TO-R1"
    ipv4: "10.0.5.2"
    prefix_length: 30
    isis_enabled: false
  - name: GigabitEthernet0/0/0/1
    description: "LINK-TO-R7"
    ipv4: "10.0.6.1"
    prefix_length: 30
    isis_enabled: true

bgp_neighbors:
  - peer_ip: "10.0.5.1"
    remote_as: 65000
    description: "eBGP-to-R1"
  - peer_ip: "192.168.0.7"
    remote_as: 65001
    description: "iBGP-to-R7"
  - peer_ip: "192.168.0.10"
    remote_as: 65001
    description: "iBGP-to-R10"
