---

hostname: R9

isis_net: "49.0001.0000.0000.0009.00"
bgp_as: 65001

loopback:
  name: Loopback0
  ipv4: "192.168.0.9"
  prefix_length: 32

interfaces:
  - name: GigabitEthernet0/0/0/0
    description: "LINK-TO-R8"
    ipv4: "10.0.8.2"
    prefix_length: 30
    isis_enabled: true
  - name: GigabitEthernet0/0/0/1
    description: "LINK-TO-R10"
    ipv4: "10.0.9.1"
    prefix_length: 30
    isis_enabled: true

bgp_neighbors:
  - peer_ip: "192.168.0.6"
    remote_as: 65001
    description: "iBGP-to-R6"
  - peer_ip: "192.168.0.10"
    remote_as: 65001
    description: "iBGP-to-R10"
