---

all:
  children:
    xrd_routers:
      vars:
        ansible_connection: ansible.netcommon.network_cli
        ansible_network_os: cisco.iosxr.iosxr
        ansible_user: clab
        ansible_password: "clab@123"
        ansible_become: false

      hosts:
        R1:
          ansible_host: 172.20.20.

        R2:
          ansible_host: 172.20.20.

        R3:
          ansible_host: 172.20.20.

        R4:
          ansible_host: 172.20.20.

        R5:
          ansible_host: 172.20.20.

        R6:
          ansible_host: 172.20.20.

        R7:
          ansible_host: 172.20.20.

        R8:
          ansible_host: 172.20.20.

        R9:
          ansible_host: 172.20.20.

        R10:
          ansible_host: 172.20.20.
